### ISSUE TITLE
The .gif file is misrecognized as a .mpg file

### ISSUE THREAD

**Issue by alexinea** [rocketRobin/myrmec#3]
As the title shows, the .gif file is misrecognized as a .mpg file. 

Is this a bug?

Thx a lot :)

**Comment by rocketRobin** [comment]
检查一下文件头，你可以用 “Binary Viewer”这个软件，然后看下文件头，把文件头留言在这里我看一下，或者直接把文件发给我, jbl-2011@163.com或者贴在此出，我看下文件的hex头。

**Comment by alexinea** [comment]
The first 10 biyes are `47 49 46 38 39 61 2C 01 E0 00`. and my code is
```
var sniffer = new Sniffer();
sniffer.Populate(FileTypes.Common);
var results = sniffer.Match(imageData.Take(20).ToArray(), true);

if (results != null && results.Any())
    return results.First();
```

Is'nt it sorting by rate priority, but the short length priority?

**Comment by rocketRobin** [comment]
I find out the reason, in your case you got results are "mpg,mpeg,gif" because the hex head above could match `"mpg mpeg", "47" ` and `"gif", "47 49 46 38 39 61"`, and when chose match all, sniffer will got mpg first,because 47 of mpg short than 47 49 46 38 39 61 for gif so it more closer to the root of metadata tree than gif. So at the things begain, if you not match all, you only get "mpg,mpeg".now I chenge the code of  [FileTypes.cs](https://github.com/rocketRobin/myrmec/blob/master/Myrmec/FileTypes.cs) ,remove 47 for mpg,mpeg. because in this page I saw 47 is a sync byte, it will repeat forever in file. see this page [FILE SIGNATURES TABLE](https://www.garykessler.net/library/file_sigs.html) , I am in this qq group 376248054.

**Comment by alexinea** [comment]
Great, in this moment, I used my own FileTypes named ImageClassTypes looks like your FileTypes.Common without any other extension format.

Thx 👍

**Comment by xingwen1987** [comment]
[.NET Core Community](https://github.com/dotnetcore) Welcome you to join！
